"""create_pr tool — tool_enhance.md productionization pass, tool #2
(2026-08-15).

TOOL PATH MIGRATION REPORT
---------------------------------------------------------------------------
Tool: create_pr
Old path: app/agents/tools.py (nested `create_pr` closure inside
    make_chat_handlers(), `_CREATE_PR_TOOL` schema dict, and the
    `_llm_generate_pr_description` helper — all three previously lived in
    the single 14,000+ line app/agents/tools.py)
New path: app/tools/git/pull_request.py (this file) — `create_pr_handler`,
    `CREATE_PR_TOOL`, `build_gh_pr_create_command`,
    `generate_pr_description`

Affected agents: only chat_agent's own AGENT_CONTRACT lists create_pr as
    an allowed_tool (confirmed via backend/tool_inventory.json's AST scan
    of every agent's real allowed_tools list). ~35 one-shot agents (e.g.
    devex_agent) call `make_chat_handlers()` and therefore have a
    create_pr handler present in their own handler dict too, but never
    advertise it in their own tools spec — now additionally enforced
    unreachable for them by the base_graph.py dispatch-authorization gate
    added earlier in this same tool-enhancement pass.
Affected modules: app/agents/tools.py (make_chat_handlers — now a thin
    wrapper calling into this module, kept as a compatibility re-export so
    existing `from app.agents.tools import ...`-style access and the
    `handlers["create_pr"]` dict-lookup pattern every real test/agent uses
    keeps working unchanged), app/agents/chat_agent.py (imports
    `generate_pr_description` and `build_gh_pr_create_command` from here
    instead of duplicating the command-building logic — the async
    diff-gathering, confirmation gate, and `gh pr create` execution stay
    in chat_agent.py since that is a genuinely different, interrupt()-
    based execution model, not something to force-merge).
Affected registries: none — app/fleet/tool_manifest.py's "create_pr"
    ToolManifestEntry is pure metadata (permissions/risk_level/timeout),
    keyed by tool NAME not file path, unaffected by this move.
Affected tests: none required changes — every real test accesses this
    tool via `handlers["create_pr"](...)` (make_chat_handlers()'s
    returned dict), never via a direct function import from tools.py, so
    the compatibility layer keeps them passing unmodified. Verified by
    real repository grep (see below), not assumed.

Old references found (via `grep -rln create_pr --include=*.py .` from
    backend/ before this move): app/agents/base_graph.py (comments only,
    no functional reference), app/agents/chat_agent.py, app/agents/
    tools.py, app/api/approvals.py (references the UNRELATED
    app.tools.git_push_tool.push_and_create_pr — a separate, REST-API-
    based, non-interactive PR mechanism used by the automated
    approval-gate flow, explicitly documented in that file's own
    docstring as distinct from this interactive chat-agent tool; not
    touched by this move), app/fleet/tool_manifest.py (metadata only),
    app/tools/git_push_tool.py (docstring mention only, not this tool),
    plus 8 test files (all access via handlers dict, see above).
Updated references: app/agents/tools.py, app/agents/chat_agent.py.
Remaining old references: none — the only two real call sites both now
    import from this module.

Runtime verification: PASS — see
    backend/docs/tool_productionization/create_pr.md's "Modularization"
    section for the exact test run and full-suite regression count.
---------------------------------------------------------------------------
"""

from __future__ import annotations

import subprocess
from typing import Any

CREATE_PR_TOOL: dict[str, Any] = {
    "name": "create_pr",
    "description": "Create a GitHub Pull Request using the gh CLI. Requires gh to be authenticated. If title and/or body are omitted, they are auto-generated by an LLM from the real diff of this branch vs base — an explicit title/body you do supply is always used as-is.",
    "input_schema": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "description": "PR title (omit to auto-generate from the real diff)",
            },
            "body": {
                "type": "string",
                "description": "PR description/body (omit to auto-generate from the real diff)",
            },
            "base": {
                "type": "string",
                "description": "Base branch to merge into (default: main)",
            },
            "draft": {
                "type": "boolean",
                "description": "Create as draft PR (default: false)",
            },
        },
        "required": [],
    },
}


def build_gh_pr_create_command(
    title: str, base: str, body: str, draft: bool
) -> list[str]:
    """Pure command-builder, shared by both real call sites (tools.py's
    sync handler and chat_agent.py's async one) — previously duplicated
    with slightly different styles in each (a real drift symptom flagged
    while auditing this tool), now built in exactly one place."""
    cmd = ["gh", "pr", "create", "--title", title, "--base", base]
    if body:
        cmd += ["--body", body]
    if draft:
        cmd.append("--draft")
    return cmd


def generate_pr_description(
    stat: str, diff: str, branch: str, base: str
) -> tuple[str, str]:
    """LLM-generated (title, body) fill-in for whichever of the two the
    caller omitted, grounded strictly in the real diff. Moved verbatim
    from app/agents/tools.py's `_llm_generate_pr_description` — only ever
    had 2 real callers (both migrated here). `_llm_generate_text` is
    imported lazily (inside the function, not at module level) to avoid a
    circular import: app.agents.tools imports FROM this module for
    create_pr_handler below, so this module cannot also import FROM
    app.agents.tools at module load time."""
    from app.agents.tools import _llm_generate_text

    prompt = (
        f"Write a GitHub pull request title and description for branch "
        f"'{branch}' being merged into '{base}', grounded strictly in the real "
        "diff below — never invent changes not shown. Respond in EXACTLY this "
        "format, no other text:\n"
        "TITLE: <one-line title>\n"
        "BODY:\n<markdown body: summary, key changes, testing notes>\n\n"
        f"=== Changed files ===\n{stat}\n\n=== Diff (truncated) ===\n{diff}"
    )
    text = _llm_generate_text(prompt, max_tokens=700)
    if not text or "TITLE:" not in text:
        return "", ""
    after_title = text.split("TITLE:", 1)[1]
    if "BODY:" in after_title:
        title, body = after_title.split("BODY:", 1)
        return title.strip(), body.strip()
    return after_title.strip(), ""


def create_pr_handler(repo_path: str, inp: dict[str, Any]) -> str:
    """The sync create_pr handler used by make_chat_handlers() (and, via
    it, the ~35 one-shot agents that reuse that handler dict — though
    create_pr itself stays unreachable for them per the dispatch-
    authorization gate in app/agents/base_graph.py). Moved verbatim from
    app/agents/tools.py, `repo_path` now an explicit parameter instead of
    a closure variable."""
    pr_title = str(inp.get("title", "")).strip()
    pr_body = str(inp.get("body", "")).strip()
    pr_base = str(inp.get("base", "main"))
    pr_draft = bool(inp.get("draft", False))
    if not pr_title or not pr_body:
        # AUDIT_Q_BATCH10 §40 "Generate PR descriptions: NO — not
        # auto-generated" — real diff of this branch vs pr_base, LLM-
        # generated to fill in whichever of title/body the caller didn't
        # supply. Explicit caller values always win — this only fills
        # gaps, never overrides an explicit title/body.
        #
        # tool_enhance.md productionization pass, tool #2 (2026-08-15) —
        # real gap found by reading this code: these 3 calls had no
        # timeout at all (unlike the gh pr create call below, which
        # already had timeout=30), so a huge diff or a hung git process
        # could block this handler indefinitely. Matches the same 30s
        # bound chat_agent.py's own _git() helper already uses for its
        # equivalent calls.
        try:
            r_stat = subprocess.run(
                ["git", "diff", f"{pr_base}...HEAD", "--stat"],
                cwd=repo_path,
                capture_output=True,
                text=True,
                timeout=30,
            )
            r_diff = subprocess.run(
                ["git", "diff", f"{pr_base}...HEAD"],
                cwd=repo_path,
                capture_output=True,
                text=True,
                timeout=30,
            )
            r_branch = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                cwd=repo_path,
                capture_output=True,
                text=True,
                timeout=30,
            )
        except subprocess.TimeoutExpired:
            return "[ERROR] git command timed out while preparing PR description"
        branch = r_branch.stdout.strip() or "HEAD"
        stat = r_stat.stdout.strip()
        diff = r_diff.stdout[:6000]
        if stat:
            gen_title, gen_body = generate_pr_description(stat, diff, branch, pr_base)
            pr_title = pr_title or gen_title
            pr_body = pr_body or gen_body
    if not pr_title:
        return "[ERROR] title is required (auto-generation failed — supply one explicitly)"
    pr_cmd = build_gh_pr_create_command(pr_title, pr_base, pr_body, pr_draft)
    try:
        r = subprocess.run(
            pr_cmd, cwd=repo_path, capture_output=True, text=True, timeout=30
        )
        return (r.stdout + r.stderr).strip() or "PR created"
    except FileNotFoundError:
        return "[ERROR] gh CLI not found — install with: sudo apt install gh"
    except Exception as e:
        return f"[ERROR] {e}"
